# Generated by Django 5.2.7 on 2025-11-02 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockups', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mockup',
            name='image',
        ),
        migrations.RemoveField(
            model_name='mockup',
            name='task_id',
        ),
        migrations.AddField(
            model_name='mockup',
            name='font',
            field=models.CharField(default='arial', max_length=100),
        ),
        migrations.AddField(
            model_name='mockup',
            name='image_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='mockup',
            name='text_color',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
        migrations.AlterField(
            model_name='mockup',
            name='text',
            field=models.CharField(max_length=200),
        ),
    ]
